version: 2
jobs:
  build:
    docker:
      - image: cimg/php:8.0-browsers
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: steelproject
          MYSQL_USER: root
          MYSQL_PASSWORD: password
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: steelproject
          MYSQL_PASSWORD: password
    steps:
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z 127.0.0.1 3306 && echo Ready && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install system packages
          command: sudo apt-get update && sudo apt-get -y install default-mysql-client zip unzip libzip-dev zlib1g-dev libicu-dev g++
      - run:
          name: Install PHP extensions
          command: |
            sudo docker-php-ext-install xsl xdebug pdo zip mbstring
            sudo docker-php-ext-enable xdebug
      - checkout
      - run:
          name: Update Composer
          command: |
            run: sudo composer self-update --1
#            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
#            php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
#            php composer-setup.php
#            php -r "unlink('composer-setup.php');"
      - run:
          name: Display version information
          command: |
            php -v
            composer --version
            mysql -V
      - run:
          name: Show Mysql databases list
          command: |
            mysql -h 127.0.0.1 -u root -ppassword --execute="SHOW DATABASES"
      - run:
          name: Install project dependencies
          command: composer install
#      - run:
#          name: Run CS tests
#          command: vendor/bin/phpcs
      - run:
          name: Create and seed the database
          command: php command migrate --seed
      - run: 
          name: Run Unit tests
          command: composer test